### ISSUE TITLE
Support more python version

### ISSUE THREAD

**Issue by Z-Y00** [Qiskit/qiskit-aer#1086]
### What is the expected behavior?
I tried to install it on python 3.9 , but there seems only support for 3.6 , 3.7 and 3.8
https://pypi.org/project/qiskit-aer-gpu/#files

https://github.com/Qiskit/qiskit-aer/issues/1085

Could you please add support for more python version?

**Comment by mtreinish** [comment]
Thanks for opening an issue on this, Python 3.9 is already supported on the git master branch already (see #1071), andl precompiled wheels (for both `qiskit-aer` and `qiskit-aer-gpu`) will be built and uploaded to pypi when qiskit-aer 0.8.0 is released. This was not possible for the last release because 3.9 support was blocked by upstream dependencies not being compatible and we only were able to use 3.9 relatively recently. I'm going to close this issue since there isn't anything to do or track here as it's just a matter of time until the next release is ready. Please feel free to reopen if I'm missing something or there is more to discuss on this topic.
