### ISSUE TITLE
kraus in the set of basis gates

### ISSUE THREAD

**Issue by yaelbh** [Qiskit/qiskit-aer#1091]
The set of basis gates of most of the simulators contains a gate named `kraus` (`qasm_simulator.py`). Does it have any effect? As far as I see, Kraus operators are defined only by the noise model.

**Comment by chriseclectic** [comment]
You can append QuantumChannel objects like SuperOp, Choi, etc to circuits directly to circuits and they will be converted to kraus instructions. Kraus is needed in the basis gate to check for transpilation to work otherwise it will try and unroll and raise an exception.

Really there should be a field for supported instructions in the providers, but there isn't yet so we have to place all custom non non-gate instructions in basis_gates for transpiler compatibility.

**Comment by yaelbh** [comment]
Thanks @chriseclectic
