### ISSUE TITLE
Wrong set of basis_gates when importing it from the noise model of any backend

### ISSUE THREAD

**Issue by LenaPer** [Qiskit/qiskit-aer#1107]
### Informations

- **Qiskit Aer version**: 0.7.2
- **Python version**: 3.8.5
- **Operating system**: macOS BigSur 11.1

### What is the current behavior?
When accessing the set of basis_gates recently changed for every backend from the noise model created via the backend, we get ['cx', 'id', 'sx', 'u3', 'x'] instead of ['id', 'rz', 'sx', 'x', 'cx'] that we get correctly by accessing it directly from the backend configurations.

### Steps to reproduce the problem
I put ibmq_16_melbourne as an example, but every backend has the same behaviour : 

from qiskit import IBMQ
IBMQ.load_account()
provider = IBMQ.get_provider(group = 'open')
from qiskit.providers.aer.noise import NoiseModel

backend = provider.get_backend('ibmq_16_melbourne')
print("From config : ", backend.configuration().basis_gates)
print("From the noise model : ",NoiseModel.from_backend(backend).basis_gates)

Theses commands return this:
From config :  ['id', 'rz', 'sx', 'x', 'cx']
From the noise model :  ['cx', 'id', 'sx', 'u3', 'x'] 

### What is the expected behavior?
We expect to have this instead : 
From config :  ['id', 'rz', 'sx', 'x', 'cx']
From the noise model :  ['id', 'rz', 'sx', 'x', 'cx']

**Comment by chriseclectic** [comment]
Thanks for pointing this out @LenaPer LenaPar. The noise model by default always included id and u3 in its basis gates unless a different default basis gate set was used when initializing a noise model. This was so that circuits could always be executed even if you didn't define noise on all gates. Since the default basis gate change for IBMQ backends this doesn't work properly anymore. I think the fix is simply to make set the NoiseModel initial basis gates to be the backends basis gates when constructing a noise model from a device.
