### ISSUE TITLE
SaveExpectationValue does not support non-Hermitian operator.

### ISSUE THREAD

**Issue by ikkoham** [Qiskit/qiskit-aer#1271]
### What is the expected behavior?

SnapshotExpectationValue supports non-Hermitian operators, but its replacement, SaveExpectationValue, does not support them.

### Sample code

```python
from qiskit import QuantumCircuit, execute
from qiskit.providers.aer.library import SaveExpectationValue
from qiskit.providers.aer.extensions import SnapshotExpectationValue
from qiskit.providers.aer import AerSimulator
from qiskit.quantum_info import Pauli, SparsePauliOp

qc = QuantumCircuit(1)
qc.append(SnapshotExpectationValue("exp", 2j * SparsePauliOp(Pauli("Z"))), [0])
print(execute(qc, AerSimulator()).result().data()) # {'snapshots': {'expectation_value': {'exp': [{'value': 2j}]}}}
```
However,
```python
qc = QuantumCircuit(1)
qc.append(SaveExpectationValue(1j * SparsePauliOp(Pauli("Z"))), [0])
execute(qc, AerSimulator()).result().data()
```
raises 
```
     62             operator = SparsePauliOp.from_operator(Operator(operator))
     63         if not allclose(operator.coeffs.imag, 0):
---> 64             raise ExtensionError("Input operator is not Hermitian.")
     65         params = _expval_params(operator, variance=False)
     66         super().__init__('save_expval', operator.num_qubits, label,

ExtensionError: 'Input operator is not Hermitian.'
```

**Comment by woodsp-ibm** [comment]
@chriseclectic Is this expected behavior of the new SaveExpectationValue? The above referenced PR in Terra, to replace the prior, now deprecated instruction with this, we had a unit test that passed with the old instruction but now fails with the new one. We were holding off on that PR pending some outcome here as to which way to proceed; would like to progress it soon though to avoid deprecation messages from running with the old instruction still.

**Comment by chriseclectic** [comment]
This was intentional since technically a quantum mechanics expectation value has to be Hermitian so the return value is real. However in principle there isn't a strict computational reason it couldn't allow non-Hermitian and return a complex like the old instruction (other than variance calculation is probably incorrect).

Do you need actually use non-Hermitian operators in current algorithms or was it just for the unit test? (A real experiment can't measure a non-Hermitian observable without decomposition into Hermitian operators and post-processing for example)

**Comment by woodsp-ibm** [comment]
I think it was more that things were usually done in opflow to allow the more general case, and this was an area that also worked. If this change is intentional, and your rationale for it seems eminently reasonable, then I guess we drop the test that ends up using Aer in this case.

**Comment by ikkoham** [comment]
I added complex support according to https://github.com/Qiskit/qiskit-terra/issues/6307, but I don't know where we need it. We may use it in Qiskit Machine learning, but I don't know these at all. Let's turn non-Hermitian operators off and see if the tests for other modules fail.

**Comment by ikkoham** [comment]
I replaced SnapshotExpectationValue with SaveExpectationValue and removed the tests for non-Hermitian operator in https://github.com/Qiskit/qiskit-terra/pull/6593.
No problem occurred in Terra and ML, so this issue is closable. Thanks.
