### ISSUE TITLE
Cannot add two expval instructions to circuit without changing labels

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-aer#1333]
### Informations

- **Qiskit Aer version**: 0.8.2
- **Python version**:
- **Operating system**:

### What is the current behavior?
The following fails because the labels, by default, are identical leading to an Exception.

```python

N = 12
qc = QuantumCircuit(N)

qc.x(range(0, N))
qc.h(range(0, N))

for kk in range(N//2,0,-1):
    qc.ch(kk, kk-1)
for kk in range(N//2, N-1):
    qc.ch(kk, kk+1)

qc.save_expectation_value(Pauli('Z'*12), range(12))
qc.measure_all()
qc.save_expectation_value(Pauli('Z'*12), range(12))
```

### What is the expected behavior?
Since there is a natural order in the circuit, the expectation values should be accessible by integer value in the order in which they appear in the circuit.  Then one does not need to mess with labels at all.

**Comment by chriseclectic** [comment]
This is intentional, not a bug, and mentioned in the API docs [here](https://qiskit.org/documentation/apidoc/aer_library.html#saving-simulator-data). 

C++ and pybind data structures for save instructions is pretty complicated so the suggested change is quite a non-trivial thing to implement, and also would require API changes to the Result class in Terra. Maybe at some point in the future if we ever have the bandwidth

**Comment by nonhermitian** [comment]
Ok makes sense.  Although it is very annoying if you do not know it is there.  Might also want to put the info in the docs here https://qiskit.org/documentation/apidoc/aer_library.html#id1 because that is where the user goes to insert the instructions into the circuit, and can completely miss the above note (like I did).

**Comment by chriseclectic** [comment]
Good idea @nonhermitian, I can move it to that section
