### ISSUE TITLE
Incorrect Probabilities on IBM Quantum Composer

### ISSUE THREAD

**Issue by the-legend-of-lia** [Qiskit/qiskit-aer#1379]
### Informations

- **Qiskit Aer version**: IBM Quantum Composer
- **Python version**: IBM Quantum Composer
- **Operating system**: Firefox on Windows 10

### What is the current behavior?
I was running an Intro to Quantum Computing workshop and realized that the same (textbook) teleportation circuit on Quantum Composer I have used for this demo in the past, is now bugged.
The IBM Quantum Composer shows wrong probabilities for the quantum teleportation circuit https://qiskit.org/textbook/ch-algorithms/teleportation.html#5.1-IBM-hardware-and-Deferred-Measurement-

### Steps to reproduce the problem
Make the following circuit in Quantum Composer.  Here it teleports the |0> state
![zero_composer_quantumteleportation](https://user-images.githubusercontent.com/16793587/139159871-0753ec75-0ffa-423c-8fc3-0bf9e8e93dc2.PNG)
Here it is supposed to teleport the |+> = H |0> state, but the probabilities are (incorrectly) the same as for teleporting the |0> state!
![plus_composer_quantumteleportation](https://user-images.githubusercontent.com/16793587/139159862-5632747e-aa8f-4b05-98fa-432f535b6e29.PNG)

### What is the expected behavior?
The same circuit on Aer simulator gives the correct probabilities.
![plus_lab_quantumteleportation](https://user-images.githubusercontent.com/16793587/139159884-3c26ba90-46e2-4610-a785-5e0f4e296784.PNG)

### Suggested solutions
I don't know what simulator Quantum Composer uses.

**Comment by the-legend-of-lia** [comment]
I now have a better understanding of the issue.  I still believe this to be a bug with Quantum Composer.
I now understand that the statevector simulator shows the probabilities / amplitudes for the _unmeasured_ outcomes.  For the outcomes which are measured somewhere in the circuit, its behavior is to behave as if it were a single shot, collapsing to a single measurement outcome.
I understand that in Qiskit Aer, this single measurement outcome that the statevector simulator collapses to is _random_, according with the probabilities of each possible measurement outcome.
However, specifically in Quantum Composer, the measurement outcome looks to me to be _deterministic_.  I suspect that the seed randomizer is not correctly re-randomizing, or at least there is no apparent way to start a new single "shot".  No matter how I delete and re-drag-in the Hadamard gate at the top-leftmost of the above quantum teleportation circuit in this thread, the measurement outcome the bottommost qubit collapses to is always 1, when it should be an equal superposition of 0 and 1.  I believe that without this feature, measurement in Quantum Composer is unrealistic and highly confusing to learn and teach with.

**Comment by sg495** [comment]
For the benefit of others who might also find this puzzling, here is a summary of the discussion I've had with @the-legend-of-lia about this issue, to the best of my understanding.

First, we look at the [teleportation circuit without measurements](https://quantum-computing.ibm.com/composer/files/new?initial=N4IgdghgtgpiBcICKBXCYAuKoAIAqMANjAA4D2AThhBgJZlg4DK6AzjgLIwSsoUyxMrEABoQARx5QEIAPIAFAKIA5JAEEmHHACYAdAAYA3AB0wtMAGNCKACYwcxiUVoAjAIy7zFxybCnx-ADmOOIA2gDMALq%2BFkE4FhHRpqYUAB4AFCS0APThAJQhofpJYC4QFBS0MBSFxSJhbpH1odolABaFjTGpnU1hrd21faFdph1hxYMNwwNjhbOWPRMz7fPRoiB2rLG0JHQMMiAAvkA), applied to the state 2/3 of the way between |0> and |L>:

![image](https://user-images.githubusercontent.com/13587235/141651205-6b0b26fb-b2f0-467a-8aa3-93f2be1f1ed5.png)

The "Probabilities" view on the bottom left shows the probabilities for joint measurement outcomes of all qubits, while the "Statevector" view on the bottom right shows the statevector as a amplitude and phase. Both views describe a situation where qubits q0 and q1 are both in the |+> state while the qubit q2 is in the state originally prepared on q0. We can easily [check this using the composer](https://quantum-computing.ibm.com/composer/files/new?initial=N4IgdghgtgpiBcIAiB7ArgIwDYwLQGMALGfAawEswBzAAgEU0IwAXNKGgFRhwAcUAnZhGbkUYGgGUhzOABoQARwgBnKAhAB5AAoBRAHJ0AghICyNAEwA6AAwBuADphK%2BLGgAmMGvcXdyGAIyWzt4OYI4K-DC0CgDaAMwAuqH4kbT48UmOjoQ0sdaZYDmx-gX8AB4AFDzkAPRxAJS5MeZJIPIeyinkPCJi6iAAvkA):

![image](https://user-images.githubusercontent.com/13587235/141651270-c8635a91-08c9-41bb-b640-5b9bf17d3015.png)

Now, as remarked above by @the-legend-of-lia, something confusing happens when a measurement is introduced. Let's look at the [same circuit with measurements on q0 and q1](https://quantum-computing.ibm.com/composer/files/new?initial=N4IgdghgtgpiBcICKBXCYAuKoAIAqMANjAA4D2AThhBgJZlg4DqtGAFjgLIwQDOKFGLEy8QAGhABHPlAQgA8gAUAogDkkAQQDKnHACYAdAAYA3AB0wtMAGNCKACYwcZqUVoAjAIwGr1l%2BbALSUEAcxxJAG0AZgBdAOtQnGtouIsLCgAPAAoSWgB6KIBKcIijVLB3CAoKWhgKErKxSM8Ypoi9co5m8usMkpa2jvi%2ByMbugK7SnpGIgcihi0mFmxmx9s6S5dg%2BASdRmJwAWgA%2BJKmA7f5BfoOTs5aTcRBHXgTaEjoGORAAXyA):

![image](https://user-images.githubusercontent.com/13587235/141651356-c8c667a2-b0bd-4214-b6af-fbde0b37434d.png)

The quantum state of q0 and q1 is pseudo-randomly collapsed by the measurements (this is a simulator, after all!), to the state |11> in the picture above. Last time I checked, this was the same behaviour displayed by the statevector simulator in Python, which is indeed extremely confusing when measurements are involved. I fully agree with @the-legend-of-lia that this severly limits the usefulness of the quantum composer as a teaching tool many real-world applications of quantum computing: indeed, this is one of the reasons why I never adopted it in the courses I hold (where I adopted the Python library instead). A simple solution could be to have different views available depending on whether the circuit has measurements or not:

1. Make the current views (probabilities, statevector and q-sphere) only available when the circuit has no measurements.
2. Make a new probabilities view only available when the circuit has measurements, displaying the probability of bistrings in the classical register (this is the information that would be returned by an actual experiment in the limit of infinitely many shots). Similarly, make a new view for the mixed state at the end of measurements ([`plot_state_paulivec`](https://qiskit.org/documentation/stubs/qiskit.visualization.plot_state_paulivec.html#qiskit.visualization.plot_state_paulivec) seems like a scalable solution).

PS. The [teleportation protocol](https://quantum-computing.ibm.com/composer/files/new?initial=N4IgdghgtgpiBcICKBXCYAuKoAIAqMANjAA4D2AThhBgJZlggA0IAjhAM5QIgDyACgFEAckgCCAZQCyOAEwA6AAwBuADphaYAMaEUAExg5VbIrQBGARnmatxtWHWsKMAOY5WAbQDMAXXtbnNy1vP3V1CgAPAAoSWgB6LwBKdw9FULAACxSLdK0I7J8mT1lc-M80oo8c%2Byzy9NhOFGcCnABaAD4cYOr1Bo4mwzq2zuC0%2B1oAMxworQBeWdlkso8S8amZ%2BYtkgC8U1fVJ6bnZpJxl-Y1149Pd4r9mEAMOANoSOgYeEABfIA)&mdash;using classical corrections&mdash;can also be implemented using the composer, and suffers from the same issue:

![image](https://user-images.githubusercontent.com/13587235/141652388-6d55572b-ce9f-4e6a-9a81-e43b290a35dc.png)

(Implementing the `0b11` correction [with the Y gate](https://quantum-computing.ibm.com/composer/files/new?initial=N4IgdghgtgpiBcICKBXCYAuKoAIAqMANjAA4D2AThhBgJZlg4CaIANCAI4QDOUCIAeQAKAUQBySAIIBlALI4ATADoADAG4AOmFpgAxoRQATGDg2citAEYBGJTt1nNYLRwowA5jg4BtAMwBdJ103T10-QK0tCgAPAAoSWgB6XwBKL28VCLAAC3TrLN1ovP9WHwUCop9M0u98p1yqrNgeFDdinABaAD4cMLqtZu5Wk0bOnrDMp1oAMxxY3QBeBYU0yu9yqdn5pes0gC90ja0ZucWF1JwAT0PAthBjbmDaEjoGfhAAXyA) is more elegant, but it would have introduced a global phase of i to the statevector, changing the colours in the picture and making it less obvious that it has the same result.)

**Comment by Swaraj1998** [comment]
The issue can also be observed simply by applying a Hadamard gate to a qubit and applying measurement on the composer. Every time it seems to collapse to state |1> no matter how many times you try.

**Comment by chriseclectic** [comment]
I'm closing this issue since it does not concern the qiskit-aer simulator.

I don't know how the composer does its simulation, but i expect it is only doing a single-shot statevector-like simulation and returning the final state probabilities conditional on a single sample of any intermediate circuit measurements. If it has a fixed seend somewhere that might explain lack of variation in these sampled outcomes for intermediate measurements, but that is just a guess.
