### ISSUE TITLE
`python setup.py install` should only copy relevant files

### ISSUE THREAD

**Issue by iyanmv** [Qiskit/qiskit-aer#1457]
### Informations

- **Qiskit Aer version**: 0.10.3
- **Python version**: 3.10.2
- **Operating system**: Arch Linux

### What is the current behavior?

I'm trying to create a `PKGBUILD` for Arch Linux and I found some issues when building from source.

If I run

```
python setup.py build
python setup.py install --root="${pkgdir}/" --optimize=1 --skip-build
```

I would expect only files in `/usr/lib/python3.10/site-packages/qiskit/`. However, all `cmake`, `contrib` and even `src` folders are copied. This is not consistent with other python packages, and I guess is not intentional.

### Steps to reproduce the problem

```
curl -O https://github.com/Qiskit/qiskit-aer/archive/refs/tags/0.10.3.tar.gz
tar -xf 0.10.3.tar.gz
cd qiskit-aer-0.10.3 && mkdir package
DISABLE_CONAN=ON python setup.py install --root=./package
ls -al package/usr
```

### What is the expected behavior?

`pyton setup.py install` should only copy relevant files (i.e. `/usr/lib/python3.10/site-packages/qiskit/`)

### Suggested solutions

**Comment by mtreinish** [comment]
My first guess is that this is an issue with `scikit-build` which probably makes aer different from most other python packages (which are using `setuptools` directly). We need to specify the c++ source files in the `MANIFEST.in` so that the sdist we publish can build the C++ extension. If the src files are polluting the installed package that points to a `scikit-build` bug to me. Looking at their bug tracker it looks like this has already been reported upstream there: https://github.com/scikit-build/scikit-build/issues/590

**Comment by iyanmv** [comment]
Apart from that bug from `scikit-build`, I think there are other issues that should be fixed in this package too. This only works if you use `pip`, but should be compatible with any backend following PEP 517 and PEP 518.

In some distros like Arch LInux, using `pip` for packaging is a no go. I have no issue building a wheel of `python-qiskit-terra` with [`python-build`](https://github.com/pypa/build) and installing with [`python-installer`](https://github.com/pypa/installer), but I can't do the same with `python-qiskit-terra`.

For example, I don't think [this](https://github.com/Qiskit/qiskit-aer/pull/1080) works if you don't use the old `setup.py build && setup.py install` approach.

**Comment by iyanmv** [comment]
I had to applied this patch on a clean chroot to be able to build aer successfully

```diff
diff --color --unified --recursive --text orig/pyproject.toml new/pyproject.toml
--- orig/pyproject.toml	2022-04-04 20:14:29.949020090 +0200
+++ new/pyproject.toml	2022-04-04 21:24:32.652332853 +0200
@@ -2,12 +2,8 @@
 requires = [
   "setuptools",
   "wheel",
-  "conan>=1.40.0",
   "scikit-build>=0.11.0",
-  "cmake!=3.17.1,!=3.17.0",
-  "ninja",
   "pybind11>2.6",
-  "oldest-supported-numpy; python_version>'3.7' or platform_machine=='aarch64' or platform_python_implementation=='PyPy'",
   "numpy==1.16.3; python_version<='3.7' and platform_machine!='aarch64' or platform_python_implementation=='PyPy'",
 ]
 build-backend = "setuptools.build_meta"
diff --color --unified --recursive --text orig/setup.py new/setup.py
--- orig/setup.py	2022-04-04 20:14:29.949020090 +0200
+++ new/setup.py	2022-04-04 21:15:05.645526211 +0200
@@ -72,7 +72,6 @@
 
 setup_requirements = common_requirements + [
     'scikit-build>=0.11.0',
-    'cmake!=3.17,!=3.17.0',
     'pybind11>=2.6',
 ]
 ```

Please, check my `PKGBUILD` [here](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=python-qiskit-aer) and see if you can replicate. I know the supported way to install `qiskit` is with `pip`, but this should work too.

**Comment by mtreinish** [comment]
Sorry I missed your comments here until just now. Yeah our intent is to support any PEP517/PEP518 backend the problem with that diff is I think it might make the pip installation from sdist break.  Like if you create a fresh venv and run `pip install --no-binary qiskit-aer qiskit-aer` this wouldn't work. I would really like to remove all the pip calls in the `setup.py` and stop using the python cmake package when the user already has cmake installed. 

I guess my other question is does the `DISABLE_CONAN` env variable not propagate down to the builder calling setup.py?

**Comment by wshanks** [comment]
I came here after noticing all the extra stuff in the qiskit aer wheel. I don't have much to add for suggesting changes that aer could make instead of waiting for scikit-build to be improved, but I just wanted to say that I had to use [this patch](https://github.com/conda-forge/staged-recipes/blob/0f7085666a31c52e633e76f467342c978b343d81/recipes/qiskit-aer/0001-drop-setup_requires.patch) to get a conda package of aer to build successfully. During package builds, conda configures pip with no remote indexes, so the scikit-build behavior of pip installing cmake fails otherwise.
