### ISSUE TITLE
Different final state precision for different qiskit-aer versions

### ISSUE THREAD

**Issue by stavros11** [Qiskit/qiskit-aer#1475]
### Informations

- **Qiskit Aer version**: 0.10.1 / 0.9.1
- **Python version**: 3.8.12
- **Operating system**: Ubuntu 20.04.4 LTS

### What is the current behavior?

I am trying to set the simulation precision to single, for example in the following script:

```Python
from qiskit import QuantumCircuit
from qiskit.providers.aer import StatevectorSimulator

circ = QuantumCircuit(2)
circ.h(0)
circ.cx(0, 1)

simulator = StatevectorSimulator(precision="single")
result = simulator.run(circ).result()
final_state = result.get_statevector(circ)
print(final_state.dtype)
```

This prints complex64 for qiskit version <= 0.33.1 (qiskit-aer 0.9.1) but complex128 for version >= 0.34.0 (qiskit-aer 0.10.1).

### Steps to reproduce the problem

I created two seperate conda environments and installed qiskit using:
```
pip install qiskit==0.33.1
```
in the first and 
```
pip install qiskit==0.34.0
```
in the second. When I execute the above script on the first environment I get complex64 as expected, while in the second environment I get:
```
check_qiskit.py:23: DeprecationWarning: The return type of saved statevectors has been changed from a `numpy.ndarray` to a `qiskit.quantum_info.Statevector` as of qiskit-aer 0.10. Accessing numpy array attributes is deprecated and will result in an error in a future release. To continue using saved result objects as arrays you can explicitly cast them using  `np.asarray(object)`.
  print(final_state.dtype)
complex128
```

If I use `np.asarray` on the final state, the precision remains to complex128.

### What is the expected behavior?

Since the simulator precision is set to single, the final state should be of complex64 type.

### Suggested solutions

I understand that there is an internal change and the simulator now returns custom state objects instead of numpy arrays. However shouldn't the returned precision still be consistent with what is set in the simulator settings?

I suspected that this is related to how I define the simulator, so I tried what is proposed [here](https://qiskit.org/documentation/tutorials/simulators/1_aer_provider.html#Simulation-Precision) to set single precision:
```Python
from qiskit import Aer
simulator = Aer.get_backend('aer_simulator_statevector')
simulator.set_options(precision='single')
```
however then the above script fails with
```
qiskit.exceptions.QiskitError: 'No statevector for experiment "<qiskit.circuit.quantumcircuit.QuantumCircuit object at 0x7f618d0b05e0>"'
```
I tried adding a `circ.save_statevector()` at the end of the circuit, but then I get:
```
AttributeError: 'QuantumCircuit' object has no attribute 'save_statevector'
```

**Comment by jakelishman** [comment]
This is a good point that we hadn't considered when we swapped over the return type - Terra's `Statevector` automatically promotes everything to double precision when we create it.  I don't know if it's enough for you, but the calculation should have still run in single precision internally, and just the very final array should get promoted to double precision.  Getting the final `Statevector` to be single precision will be a bit trickier, because all of `qiskit.quantum_info` assumes double precision (in part because Python's floats are doubles).

For your second point: I'm guessing that in your second example, you tried to build the circuit before the line `simulator = Aer.get_backend(...)`.  If you move that line to the top of the script, the `QuantumCircuit.save_statevector` method should work again (`qiskit.Aer` is a lazy-loader of Aer - it doesn't actually import it until you use the object somehow).  The output will still be a `Statevector` in double precision, but the calculations internally should be single.

**Comment by stavros11** [comment]
Thank you for the quick reply.

> This is a good point that we hadn't considered when we swapped over the return type - Terra's `Statevector` automatically promotes everything to double precision when we create it. I don't know if it's enough for you, but the calculation should have still run in single precision internally, and just the very final array should get promoted to double precision. 

For my case it is sufficient to know that the simulation runs in single precision, regardless of the final result type.

> For your second point: I'm guessing that in your second example, you tried to build the circuit before the line `simulator = Aer.get_backend(...)`. If you move that line to the top of the script, the `QuantumCircuit.save_statevector` method should work again

Indeed, that's right. If I define the simulator before the circuit it works and the issue with precision still remains. Note however that the [example provided in the docs](https://qiskit.org/documentation/tutorials/simulators/1_aer_provider.html#Saving-the-final-statevector) for saving the final statevector does not work as the simulator is defined after the circuit.

**Comment by hhorii** [comment]
[This example](https://qiskit.org/documentation/tutorials/simulators/1_aer_provider.html#Saving-the-final-statevector) works because [`Aer` is loaded first](https://qiskit.org/documentation/tutorials/simulators/1_aer_provider.html#The-Aer-Provider) in the notebook. But maybe it is better to swap circuit construction and simulator instantiation as an example.

**Comment by hhorii** [comment]
I would like to close this issue. Please re-open this if a problem still remains.
