### ISSUE TITLE
`parameter_binds` behavior is different from that of Terra's documentation

### ISSUE THREAD

**Issue by t-imamichi** [Qiskit/qiskit-aer#1551]
### Informations

- **Qiskit Aer version**: 0.10.4
- **Python version**: 3.10.5
- **Operating system**: macOS 12.4

### What is the current behavior?

`parameter_binds` of `IBMQBackend.run` or `execute` are explained as follows.
> parameter_binds (Optional[List[Dict[[Parameter](https://qiskit.org/documentation/stubs/qiskit.circuit.Parameter.html#qiskit.circuit.Parameter), float]]]) – List of Parameter bindings over which the set of experiments will be executed. Each list element (bind) should be of the form {Parameter1: value1, Parameter2: value2, …}. All binds will be executed across all experiments; e.g., if parameter_binds is a length-n list, and there are m experiments, a total of m x n experiments will be run (one for each experiment/bind pair). 

[Terra's execute](https://qiskit.org/documentation/apidoc/execute.html)
[Terra's assemble](https://qiskit.org/documentation/stubs/qiskit.compiler.assemble.html)
[IBMQBackend.run](https://qiskit.org/documentation/stubs/qiskit.providers.ibmq.IBMQBackend.run.html)

The value part is expected to be a value for Terra and IBMQ provider.
 
But, Aer seems to expect a list of values.

Which behavior is correct?

### Steps to reproduce the problem

```python
from qiskit import QuantumCircuit, Aer, IBMQ
from qiskit.circuit import Parameter

qc = QuantumCircuit(1, 1)
param = Parameter('x')
qc.p(param, 0)
qc.measure(0, 0)

prov = IBMQ.load_account()

def test(parameter_binds):
    backend = Aer.get_backend('aer_simulator')
    try:
        print('\naer')
        print(backend.run(qc, parameter_binds=parameter_binds).result().get_counts())
    except Exception as ex:
        print(repr(ex))

    backend = prov.get_backend('ibmq_qasm_simulator')
    try:
        print('\nibmq_qasm_simulator')
        print(backend.run(qc, parameter_binds=parameter_binds).result().get_counts())
    except Exception as ex:
        print(repr(ex))

parameter_binds = [{param: 0}]
print('\nCase 1: parameter_binds =', parameter_binds)
test(parameter_binds)

parameter_binds = [{param: [0]}]
print('\nCase 2: parameter_binds =', parameter_binds)
test(parameter_binds)
```

output w/ qiskit-aer 0.10.4 and qiskit-ibmq-provider 0.19.2
```
Case 1: parameter_binds = [{Parameter(x): 0}]

aer
Simulation failed and returned the following error message:
ERROR: Failed to load qobj: [json.exception.type_error.302] type must be array, but is number
[]

ibmq_qasm_simulator
{'0': 4000}

Case 2: parameter_binds = [{Parameter(x): [0]}]

aer
{'0': 1024}

ibmq_qasm_simulator
CircuitError('Expression cannot bind non-numeric values ({Parameter(x): [0]})')
```

### What is the expected behavior?

Same behavior between aer and ibmq-provider

**Comment by hhorii** [comment]
We think that this is an issue of qiskit-ibmq-provider. Aer takes a list of values for each parameter.

**Comment by t-imamichi** [comment]
ibmq-provider invokes `assemble` to bind parameters. Do you mean that Terra's documentation and implementation are wrong?

**Comment by hhorii** [comment]
> Do you mean that Terra's documentation and implementation are wrong?

No. This is not an issue of Terra. This is an issue in qiskit-ibmq-provider if it is designed to use Aer's parameterized qobj.

`parameter_binds` specifications of qiskit-aer and `assemble()` are different. To use Aer's parameterized qobj, qiskit-ibmq-provider should not use `assemble()` which just [expand](https://github.com/Qiskit/qiskit-terra/blob/56501cc6734e6d3228474bcbd38c145afbe334e7/qiskit/compiler/assembler.py#L204-L206) circuits, and should use `AerSimulator._assemble()`.

Types of `parameter_binds` of `AerSimulator._assemble()` and `assemble()` are different and Aer may be able to support  the type of `assemble()`.

**Comment by t-imamichi** [comment]
OK. I ask it to qiskit-ibm-provider repo. It has the same issue. https://github.com/Qiskit/qiskit-ibm-provider/issues/370

**Comment by mtreinish** [comment]
The fundamental issue you're seeing is that `parameter_binds` is not a standard interface, it's custom between every provider and just happens to have a name collision between aer and ibmq/ibm. Each implementation of it is custom to a provider. This is because most providers don't natively supported running parameterized circuits. For Aer in particular it has extra features that allow it to efficiently bind multiple parameter values per circuit without copying which is why the input is a list of dicts with list values. While the ibmq/ibm provider doesn't have this kind of support because real backends don't support that kind of binding, so at submission time each parameter must have a defined value. That's why the ibm provider's `parameter_binds` only takes a single value, since under the covers it's just calling `QuantumCircuit.bind_parameters()` before building the qobj. 

I agree the tricky piece here is that the ibmq provider lets you run on ibm's hosted aer but fails to expose the same feature set of the local aer provider. It treats the aer backend as basically any hardware backend which limits the functionality. @hhorii is correct that this is an issue in the ibm provider especially if you want to use multiple bind values when running on the ibmq hosted aer backend. One bad alternative you can use in the meantime is manually constructing the `parameterizations` field when using the ibm/ibmq provider and pass that in to `run()` directly (which should put it in the proper place in the qobj payload). The format isn't the most user friendly though as it is nested lists of the form: `[[[circuit_index, parameter_number], [bind_values]], ...]`

**Comment by ikkoham** [comment]
Perhaps Primitives absorb these differences. (One of the motivation of introducing primitives.)

**Comment by hhorii** [comment]
I believe that @t-imamichi satisfied with the comment of @mtreinish.
