### ISSUE TITLE
Issue with nested if_test

### ISSUE THREAD

**Issue by cklee982** [Qiskit/qiskit-aer#1665]
### Informations

- **Qiskit version**: 0.38.0
- **Qiskit Aer version**: 0.11.0
- **Python version**: 3.10.8
- **Operating system**: Mac OS 12.6, M1 Max

### What is the current behavior?

Does not produce expected output when nested if_test statement is used. 

### Steps to reproduce the problem

```
from qiskit.circuit import QuantumCircuit
from qiskit import IBMQ, Aer, QuantumCircuit, QuantumRegister, ClassicalRegister, execute
import numpy as np  

backend_sim = Aer.get_backend('qasm_simulator')
pi = np.pi

q = QuantumRegister(3)
c = ClassicalRegister(3)
circuit = QuantumCircuit(q, c)
circuit.initialize('010', circuit.qubits)

circuit.measure(q[0], c[0])
circuit.measure(q[1], c[1])

with circuit.if_test((c[0], 1)):
    with circuit.if_test((c[1], 0)):
        circuit.x(q[2])

with circuit.if_test((c[0], 0)):
    with circuit.if_test((c[1], 1)):
        circuit.x(q[2])

circuit.measure(q, c)

job = backend_sim.run(circuit, backend_sim, shots = 100)
results = job.result().get_counts()
print(results)
```
Output: {'010': 100}

### What is the expected behavior?
Expected output bit string is '110'

### Suggested solutions
N/A

**Comment by jakelishman** [comment]
Chee-Kong and I spoke about this on Slack briefly, and from my looking at the problem, Terra seems to be constructing the problem correctly.  I think the issue is that the inlining of control flow in jump/mark instructions within Aer isn't enforcing that the control-flow block stays together as a basic block.  The jump/mark instructions alone lose some of the data-flow ordering of the tree structure of control-flow since they don't include the clbits of the control-flow block.

Assuming I'm right (I'm fairly confident I am), I can fix it tomorrow.

**Comment by jakelishman** [comment]
I've made #1666 which hopefully should fix this issue.
