### ISSUE TITLE
Simulators stopped accepting float input for shots

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-aer#1754]
### Informations

- **Qiskit Aer version**: latest
- **Python version**:
- **Operating system**:

### What is the current behavior?
Previous versions of Aer allowed for setting shots values using things like `shots=1e4`.  The latest version stopped doing this and gives a cryptic error:

```
TypeError: (): incompatible function arguments. The following argument types are supported:
    1. (self: qiskit_aer.backends.controller_wrappers.AerConfig, arg0: int) -> None

Invoked with: <qiskit_aer.backends.controller_wrappers.AerConfig object at 0x7f7291bd0730>, 10000.0
```

### Steps to reproduce the problem
Run a simulation, e.g. via the fake backends using a float representation of an int

### What is the expected behavior?

This represents a breaking change, and should probably be fixed by casting.

**Comment by jakelishman** [comment]
We should fix this temporarily in a bugfix release (since it is breaking), but downstream code also shouldn't be doing that, and they're just lucky that it's worked so far at all.  I'd support deprecating this behaviour, since in the new config form it will require additional code overhead to allow these false types.

It only ever worked because the JSON spec (Aer previously used JSON to communicate across the C++/Python boundary) only has one number type - not that users should need to care about the reason why - and in languages that do distinguish, a `float` is not an `int`.  Python built-ins that want an integer input will also produce an error if you give them a float, such as `int("0x1a", base=16.0)`.

**Comment by nonhermitian** [comment]
I am fine with that.

**Comment by hhorii** [comment]
I believe I can find similar phenomena in other configurations. I guess that type checking can be in `Backend` if definition of types exist for options, but unfortunately not now. Because Aer 0.12.0 introduced strict manner for bindings then I would like to add some type checking and casting rules in `AerBackend`.
