### ISSUE TITLE
qiskit-aer stopped providing manylinux wheels for ppc64le & s390x since 0.12.0

### ISSUE THREAD

**Issue by mgiessing** [Qiskit/qiskit-aer#1785]
### Informations

- **Qiskit AER version**: 0.12.0
- **Operating system**: linux/ppc64le & linux/s390x

### What is the current behavior?
It doesn't provide wheels for the mentioned CPU architectures. 
Not sure why it stopped building the wheels, because in 0.11.2 it still build & uploaded wheels to pypi

### What is the expected behavior?
Build wheels for ppc64le & s390x :)

**Comment by hhorii** [comment]
Currently, storage of qiskit-aer in PyPI is over the limit and uploading binary for some architecture were failing. We are now waiting for the limit is increased.

- https://github.com/pypi/support/issues/2677

**Comment by mtreinish** [comment]
Unfortunately the non-x86 wheel uploads to PyPI failed because of project quota limits: https://github.com/Qiskit/qiskit-aer/actions/runs/4378395897/jobs/7663086771#step:9:33 which is preventing us from uploading any new package files (either for the missing files in 0.12.0 or any future releases)

We've requested a larger quota here: https://github.com/pypi/support/issues/2677 but we're still waiting for a response from the pypi team.

In the meantime you can download the wheels from the failed CI job's artifact at the bottom of: https://github.com/Qiskit/qiskit-aer/actions/runs/4378395897 which will be a zip file containing all the release artifacts.

**Comment by mgiessing** [comment]
Thanks for clarification - that helps!
