### ISSUE TITLE
Add Aer tests from terra

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-aer#188]
### What is the expected behavior?
There are a few tests that were in Terra when the simulator was there. These are now being removed. We should move those to this repository. They can be found in:
`qiskit-terra/test/python/aer_provider_integration_test/`
Chief among them are 
`test_aer_qobj_headers.py`
`test_multi_registers_convention.py`

These are being removed in https://github.com/Qiskit/qiskit-terra/pull/2201

**Comment by Riuchando** [comment]
Hello, I would like to help contribute to the project and thought this might be useful to work on, is this still unaddressed?

**Comment by jkelso662** [comment]
Hi guys! @Riuchando are you currently working on this? I don't see these tests in qiskit-aer yet so I'm assuming this issue is still todo? 

@ajavadia if this issue is still valid, and if Riuchando isn't working on it, could you provide some more info on this? E.g. where would make sense to put these tests and what might need to be done to get them running successfully? Thanks!

**Comment by ajavadia** [comment]
I think this issue had been addressed for some time
