### ISSUE TITLE
Slow performance with noise

### ISSUE THREAD

**Issue by dcmckayibm** [Qiskit/qiskit-aer#199]
Performance from 0.1.1 to 0.2 slowed down considerably with noisy circuits 

Almost 1hour to run https://github.com/Qiskit/qiskit-tutorials/blob/master/qiskit/ignis/randomized_benchmarking.ipynb

### Informations

- **Qiskit Aer version**:
- **Python version**:
- **Operating system**:

**Comment by chriseclectic** [comment]
This appears to be due to circuit optimization passes running when they aren't needed for small qubit circuits (when these passes taking longer than the actual simulation time). This is then compounded by them needing to run each shot for noisy simulations.

I have a work around is in #200 that appears to fix the problem by disabling these passes for small numbers of qubits, but in the future we need to revisit how these optimisations are implemented so they can be more selectively applied to avoid this kind of slowdowns @hhorii @atilag .

**Comment by atilag** [comment]
I think we have fixed this issue in 0.2.0, could you confirm @dcmckayibm ?

**Comment by dcmckayibm** [comment]
I tested @chriseclectic 's PR, but were there further changes?

**Comment by chriseclectic** [comment]
Closing this, since further improvements will be through enhancements and optimizations.
