### ISSUE TITLE
Remove openblas.lib/.7z from the wheel package

### ISSUE THREAD

**Issue by atilag** [Qiskit/qiskit-aer#203]
### Informations

- **Qiskit Aer version**: 0.2.0
- **Python version**: All
- **Operating system**: All

### What is the current behavior?
When we build the wheels package, the openblas.lib static library gets added to the Windows package as well as the compressed version openblas.7z. The openblas.lib is quite large and we don't really need it on Windows because the build system can deal withe the compressed version. The rest of platforms don't need this file at all, so it should not being included.

### Steps to reproduce the problem
Create the wheels package. The Windows wheel has both files: openblas.7z (which is correct) and openblas.lib (which shouldn't be there).

### What is the expected behavior?
openblas.lib shouldn't be there in the Windows wheel, and openblas.7z shouldn't be there in Linux/MacOS platforms.

### Suggested solutions
Add openblas.lib as an exception in the MANFIEST.in file.
For not including openblas.7z in Linux/MacOS wheeks, we will require other changes.

**Comment by woodsp-ibm** [comment]
pip installing qiskit-aer or 0.2.0 into our travis build/test of Aqua seems to be causing the following core dump that never happened with prior versions.
 `test_saving_and_loading_e2e (test_caching.TestCaching) ... /home/travis/.travis/functions: line 104:  6363 Floating point exception(core dumped) python test/custom_tests.py 0 -end 34
The command "python test/custom_tests.py 0 -end 34" exited with 136.`
Since only a couple of our unit tests use Aer as part of the test, the failing one above is not one of them, we have removed it from the build for now and the above passes again as before.

**Comment by hhorii** [comment]
@chriseclectic I believe we can remove blas dependency by re-writing matrix multiplication instead of calling BLAS in https://github.com/Qiskit/qiskit-aer/blob/0.2.1/src/framework/matrix.hpp#L688-L844.

Currently following codes use them. They are not hotspot in simulator.
https://github.com/Qiskit/qiskit-aer/blob/0.2.1/src/framework/utils.hpp#L796
https://github.com/Qiskit/qiskit-aer/blob/0.2.1/src/framework/utils.hpp#L815

**Comment by atilag** [comment]
Fixed in [this commit](https://github.com/Qiskit/qiskit-aer/commit/05049d90b00ea2ebeb579d5031d3dd24cb96f08d#diff-97c91a104c431d0c365565d3ac03ac13). It's part of the `openpulse-sim` branch, so it will land in `master` once merged.
