### ISSUE TITLE
Aer does not catch circuits that are too big for qasm simulator

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-aer#204]
### Informations

- **Qiskit Aer version**: master
- **Python version**:
- **Operating system**: osx

### What is the current behavior?
```python

from qiskit import QuantumRegister, ClassicalRegister
from qiskit import QuantumCircuit, Aer, execute

q = QuantumRegister(50)
c = ClassicalRegister(2)
qc = QuantumCircuit(q, c)

qc.h(q[0])
qc.cx(q[0], q[1])
for kk in range(2,50):
    qc.t(q[kk])
qc.measure(q[0], c[0])
qc.measure(q[1], c[1])
backend = Aer.get_backend('qasm_simulator')
job_sim = execute(qc, backend)
```
gives

```
python(28032,0x70000d836000) malloc: can't allocate region
*** mach_vm_map(size=18014398509481984) failed (error code=3)
python(28032,0x70000d836000) malloc: *** set a breakpoint in malloc_error_break to debug
Segmentation fault: 11
```
obviously this can be caught ahead of time, and a check should be against `n_qubits=MAX_QUBIT_MEMORY` in the config, but it is not.

**Comment by chriseclectic** [comment]
I think in this case it is executing on the extended stabilizer simulator (Clifford + T), which in principle can support up to 63 qubits, but because of the T gate depth it is running out of memory.

@padraic-padraic Would it be possible to add a check to the `required_memory_mb` function that checks the depth of non-Clifford gates to estimate the resource requirements?

**Comment by padraic-padraic** [comment]
There is code for checking the memory requirements as part of the state. Digging into this, the bug seems to be because `State::required_memory_mb` returns a `size_t`, which was being converted to an `int` in `AER::Simulator::QasmController::validate_memory_requirements` and overflowing to 0. 

I'll submit a pull request with the fix!
