### ISSUE TITLE
ImportError: cannot import name 'Aer' from 'qiskit' (C:\Users\sandi\anaconda3\Lib\site-packages\qiskit\__init__.py)

### ISSUE THREAD

**Issue by aaaalexjorden** [Qiskit/qiskit-aer#2061]
*BUG TEMPLATE* 

### Informations

- **Qiskit AER version**:
- **Operating system**:

### Suggested solutions

---

*FEATURE REQUEST TEMPLATE*  

### What is the expected behavior?

---

*ENHANCEMENT REQUEST TEMPLATE*

**Comment by jakelishman** [comment]
Thank you for the report.  This is expected behaviour of Qiskit 1.0 and noted in its release notes and deprecated in Qiskit 0.46 (our suggested upgrade path is to first upgrade to Qiskit 0.46, see the warnings that appear there so they can be fixed before finalising the upgrade to Qiskit 1.0).

The drop-in replacement for `qiskit.Aer` is `qiskit_aer.Aer`.
