### ISSUE TITLE
Support for PrimitivesV2

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-aer#2078]
The primitives in `qiskit_aer/primitives` implement `qiskit_aer.primitives.sampler.Sampler` and `qiskit_aer.primitives.estimator.Estimator` that are subclassing `qiskit.primitives.base.base_sampler.BaseSamplerV1` and `qiskit.primitives.base.base_estimator.BaseEstimatorV1`. With the introduction of [BaseSamplerV2](https://docs.quantum.ibm.com/api/qiskit/qiskit.primitives.BaseSamplerV2) and [BaseEstimatorV2](https://docs.quantum.ibm.com/api/qiskit/qiskit.primitives.BaseEstimatorV2), it would be great to have `qiskit_aer.primitives.sampler.SamplerV2` and and `qiskit_aer.primitives.estimator.EstimatorV2`.

**Comment by ikkoham** [comment]
I implemented EstimatorV2Converter https://github.com/Qiskit/qiskit/pull/11899. It may be useful for EstimatorV2.
Unfortunately, it is not possible to implement SamplerV2Converter because result data are completely different.
But, there are no advantages for SamplerV2 because simulator specific improvement does not exist. BackendSamplerV2 + AerSimulator is good choice.

**Comment by kevinsung** [comment]
In qiskit-ibm-runtime 0.22, there will be a "[local testing mode](https://github.com/Qiskit/documentation/blob/8f44c18c1a33eac1c2e81fa91fe364c031eb92b3/docs/api/migration-guides/local-simulators.mdx#L59)". So if we add SamplerV2 here in Aer, it seems there will be two ways to do the same thing:
- Use SamplerV2 from Aer
- Use SamplerV2 from qiskit-ibm-runtime, with an Aer backend.

In general, should we recommend one over the other? I'm thinking from a documentation perspective.

**Comment by kevinsung** [comment]
Ah, one difference I noticed is that EstimatorV2 might support `approximation=True` to get a result without statistical sampling error.

**Comment by kielpins-qctrl** [comment]
@ikkoham 
> But, there are no advantages for SamplerV2 because simulator specific improvement does not exist.

I primarily use Aer as a way to test code for circuit design before deploying to QPUs. Since the recent changes in `qiskit-ibm-runtime` behaviour, I must use SamplerV2 on IBM QPUs in order to retrieve bitstrings. Analysis of the results requires a consistent interface, so without SamplerV2, Aer is not usable for me.

**Comment by garrison** [comment]
> I primarily use Aer as a way to test code for circuit design before deploying to QPUs. Since the recent changes in `qiskit-ibm-runtime` behaviour, I must use SamplerV2 on IBM QPUs in order to retrieve bitstrings.

You might want to look at the guide to using `SamplerV2` from qiskit-ibm-runtime in local mode, with `AerSimulator` as backend, after upgrading to qiskit-ibm-runtime 0.22.0 or later:  https://docs.quantum.ibm.com/api/migration-guides/local-simulators#aersimulator

**Comment by kielpins-qctrl** [comment]
@garrison Thanks for flagging this. I was able to successfully run that migration guide. However, the circuit metadata is still absent from the result object, [in the same way that I reported for fake backends](https://github.com/Qiskit/qiskit-ibm-runtime/issues/1551). Due to this inconsistency with results from real QPUs, I'm no longer able to mock QPU runs with `AerSimulator` for testing.

**Comment by ikkoham** [comment]
EstimatorV2 here https://github.com/Qiskit/qiskit-aer/pull/2088
