### ISSUE TITLE
Idle qubit schedule utility function

### ISSUE THREAD

**Issue by chriseclectic** [Qiskit/qiskit-aer#211]
### What is the expected behavior?

I would like to see a function in the `noise.utils` folder that can be used to convert a circuit to a gate level "schedule" based on which gates could (in principle) be done in parallel, and insert identities on idle qubits during each time step. This is an important tool for doing more accurate noise simulations of T1 relaxation since an error can be added to the idle qubit identities to simulate relaxation.

This insertion should respect barriers (so gates with a barrier between them will always be in a seperate time step), and insert different identities for the different length gates. I think initially having just two identity types: one for CX gates and one for single qubit (u3) gates is a good start. This could be implemented by using the label option for the identity gates so we have "id_cx" and "id_u3" as their labels for reference in the noise model.

**Comment by yirkajk** [comment]
I copied the new idle scheduler function from #237, and it's working well for my purposes. But, the different labels for the id gates were difficult to work with for two reasons. 
- First, there is almost no mention in the tutorials and documentation (beyond the source code) that `noise_model` depends on gate labels, not gate names. Only the [Custom Gate Noise Tutorial](https://github.com/Qiskit/qiskit-tutorials/blob/master/qiskit/aer/custom_gate_noise.ipynb) mentions it, so someone working with id gates can easily miss it. (Note that this idle utility could be one of the first experiences a user has with automatically generated labels.) Right now, it's non-obvious that the gates added by this utility will not respond to noise on generic "id" gates.
- Second, because of the many different labels, it's cumbersome to apply noise to all of the gates.

I would suggest making noise depend on names instead of labels, but the discussion in #207 (continuing in Qiskit/qiskit-terra#2393) suggests idle gates are an area where labelling is useful. So, I suggest the noise documentation and/or the idle scheduler documentation needs to be updated in order for the idle scheduler to be usable. 

Second, perhaps an argument could be added to the scheduler function which allows the user to provide a default label?

**Comment by gadial** [comment]
Thanks for the helpful feedback! It seems to me the best course of action to add a parameter for choosing the label to use (can be a string or a dict from gates to strings) and improving the documentation.

**Comment by gadial** [comment]
I've added the parameter in b238d15f33b377c21032978f38f0a95a80450a20.

**Comment by atilag** [comment]
I think it's safe to close this issue, it's been a while without activity, also last comment suggest this was already tackled?

**Comment by chriseclectic** [comment]
Equivalent functionality will be added soon once we finish scheduled circuits in Terra
