### ISSUE TITLE
Update documents and tutorials

### ISSUE THREAD

**Issue by doichanj** [Qiskit/qiskit-aer#2114]
### What is the expected behavior?

Since Qiskit version 1.0 is released, a lot of changes of interfaces has been implemented also in Aer. However there are still older documents and tutorials are remaining. 

- Provide detailed documentations and tutorials for V2 primitives (`qiskit_aer.primitives.EstimatorV2` and `qiskit_aer.primitives.SamplerV2`) instead of using `AerSimulator.run()` (see README of Aer)
- Remove qasm_simulator, statevector_simulator and replace with AerSimulator
- Remove other deprecate features from documents and tutorials 

Please also refer to migration guide for Qiskit 1.0 for details (https://docs.quantum.ibm.com/api/migration-guides/qiskit-1.0)

This issue will be solved by:
- #2160

**Comment by HuangJunye** [comment]
Would love to see the update on documentation, especially V2 primitives. A few users didn't know that there is already V2 primitives in aer, probably because they can't see V2 primitives in the documentation. I know updating all tutorials is a lot of work. Is it possible to just build the API reference for EstimatorV2 and SamplerV2 first?

**Comment by anonymousr007** [comment]
Hi @HuangJunye and @doichanj, Nice to meet you. 

I am Rishabh Singh, and I have been learning about quantum computing since 2020. 

- Experience - Qiskit, Pennylane and Cirq.
- Participation - Quantum Hackathons, Qiskit Summer School and IBM Quantum Challenges.
- Open Source Contribution - Cirq, Pennylane, Scikit-Learn.
- I am interested in this issue and want to contribute.

Best Regards 
Rishabh Singh
[LinkedIn](https://www.linkedin.com/in/anonymousr007/) | [GitHub](https://github.com/anonymousr007)

**Comment by divshacker** [comment]
Hey @doichanj @HuangJunye , I can take this up. I had a past experience in improving tutorials before through QAMP, I think I am good to do this.
Thanks

**Comment by doichanj** [comment]
I think it is good to merge updated documents in #2160, thank you

**Comment by doichanj** [comment]
I think this #2162 can be merged in this issue

**Comment by doichanj** [comment]
Please consider adding API docs for V2 primitives #2163

**Comment by divshacker** [comment]
Please assign this issue to me @doichanj before merging my PR
Thanks
