### ISSUE TITLE
Support global seed

### ISSUE THREAD

**Issue by frankharkins** [Qiskit/qiskit-aer#2250]
### What is the expected behavior?

It'd be nice for testing to be able to set a global seed. This means we wouldn't have to explicitly set a seed in all our code examples. Either reading an environment variable or supporting setting a module-wide variable would be great.

**Comment by jakelishman** [comment]
Honestly, for testing, this is typically a bad idea, because it's way easy to end up with a test suite whose success is dependent on the order the tests run, or whether they run in parallel or anything.  Testing should always fix random seeds manually, and within the control of the test.

Similar for examples in documentation or anything like that - your documentation build success can suddenly depend on what order the test suites are run in, and everything like that.

The scientific Python community are currently working on a document strongly discouraging even the exposure of global random state, especially with Python 3.13 introducing experiment free-threaded versions of Python: https://scientific-python.org/specs/spec-0007/.

**Comment by frankharkins** [comment]
Right, that makes sense, thanks. I was hoping make our notebooks deterministic to reduce diff noise but that's quite a niche use-case and only a mild inconvenience. I'll find a workaround.

**Comment by jakelishman** [comment]
Oh no, I totally agree - the notebooks would be a lot better being deterministic (not only because for me with a currently dodgy and limited internet connection, I can't actually `git fetch` Qiskit/documentation without eating a _whole_ chunk of data I don't have to spare).  Personally, I think seeding the simulators in the notebooks is a fairly decent habit to teach people, though I get it's not necessarily the prettiest.
