### ISSUE TITLE
Aer backend giving depreciation warnings using terra master

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-aer#227]
### Informations

- **Qiskit Aer version**: master
- **Python version**:
- **Operating system**:

### What is the current behavior?
```python
/miniconda3/lib/python3.7/site-packages/qiskit/providers/aer/backends/aerbackend.py:119: DeprecationWarning: The as_dict() method is deprecated, use to_dict().
  config = original_config.as_dict()
/miniconda3/lib/python3.7/site-packages/qiskit/providers/aer/backends/aerbackend.py:54: DeprecationWarning: The as_dict() method is deprecated, use to_dict().
  return obj.as_dict()
```

**Comment by atilag** [comment]
We do have a `NoiseModel::as_dict()` method that we may want to change to `.to_dict()`  the same way Terra did, otherwise our `AerJSONEncoder` class won't know how to serialize `NoiseModel` objects.

This is changing the API of an important component, just making sure @chriseclectic and @gadial are fine with this change, and what implications have (more than changing the tutorials).
I'll put a depreaction warning in our `NoiseModel::as_dict()` method so we can remove it for 0.3.x or 0.4.x.

**Comment by atilag** [comment]
For the sake of consistency, I have changed all our `.as_dict()` API methods, to `to_dict()`.
