### ISSUE TITLE
unit-tests-latest-qiskit fails since mid-Oct

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-aer#2270]
### Informations

- **Qiskit Aer version**: dev
- **Python version**: 3.11
- **Operating system**: `ubuntu-latest` in CI

### What is the current behavior?

Since Oct 17, there are 24 failing tests when Qiskit dev is installed. There is a chance this is a Qiskit issue that introduced a regression in the stable API, I didn't check it. If so, please open an issue in Qiskit/qiskit

### Steps to reproduce the problem

Go to https://github.com/Qiskit/qiskit-aer/actions/workflows/unit-tests-latest-qiskit.yml?page=2 and see the errors.

### What is the expected behavior?

Aer should work with Qiskit dev branch, ie. main

**Comment by gadial** [comment]
This is a well-known problem, that should be fixed in #2265 . Basically, `save_expval` was extended with a smart truncation technique allowing aer to run on circuits compiled vs many-qubits backends, but the implementation had a small bug causing problems in several edge cases. Should be ok once the PR is merged.

**Comment by Cryoris** [comment]
Nice! But it would be interesting to know what in Qiskit triggered these failing tests... do you think it has something to do with how you now fixed the Paulis being mapped to the qubits?

**Comment by 1ucian0** [comment]
Since Dec 11th, unit-tests-latest-qiskit are back. Thanks!
