### ISSUE TITLE
Dependencies for the Pulse Simulator

### ISSUE THREAD

**Issue by dcmckayibm** [Qiskit/qiskit-aer#249]
Bring over the proper dependency files for the pulse simulator.

**Comment by nonhermitian** [comment]
The dependencies have been moved into my branch:

https://github.com/nonhermitian/qiskit-aer/tree/openpulse

However, the runtime files need OpenPulse to be installed so that they have a place to import the Cython modules from.  Therefore, the Cython files need to be built and installed with the current build system (which I probably need help with).
