### ISSUE TITLE
Add tests for marking sure conditional instructions works as expected

### ISSUE THREAD

**Issue by atilag** [Qiskit/qiskit-aer#277]
We need tests for testing that conditional operations logic work as expected.
Not all operations can have conditionals (like `barrier`), so if a qobj is sent to the simulator
with conditionals in unexepected operations, the simulation will error.
Although, we need to test that those operations allowed to have conditionals, work as expected too.

**Comment by SatyaKuppam** [comment]
I can work on this.

**Comment by chriseclectic** [comment]
Thanks @SatyaKuppam! There was actually several tests added after this issue was created which you can see here:

https://github.com/Qiskit/qiskit-aer/blob/master/test/terra/backends/qasm_simulator/qasm_conditional.py

https://github.com/Qiskit/qiskit-aer/blob/master/test/terra/reference/ref_conditionals.py

But it would be still good to fill in the gaps and increase coverage. Some additional tests could be:

* Testing making conditionals on unsupported instructions raises an exception (ie barrier, measure, reset).
* Testing conditionals on additional gates (eg u1, u2, u3)

**Comment by SatyaKuppam** [comment]
I see. Thanks for the info. I will work on increasing the test coverage.
