### ISSUE TITLE
Aer installation fails in multiple cases

### ISSUE THREAD

**Issue by quantumjim** [Qiskit/qiskit-aer#65]
### Informations

- **Qiskit AER version**: 0.1
- **Operating system**: Multiple/unknown

### What is the current behavior?

Error when importing Aer in [trinket](https://trinket.io/python3/3aa12110e0) and [Google Colab](https://colab.research.google.com/drive/1bWHhoMmLTllLjd4BN2v3Sbzwi1-vVRnP).

I've also seen people have the problems on Windows. I suggested installation from source, but they had no desire to take that step.

### Steps to reproduce the problem

See the above links.

### What is the expected behavior?

Aer should be importable.

**Comment by atilag** [comment]
Ok, so after tracking down the problem in these platforms, I just find out that Debian based distributions (which seems to be the distribution they use under the hoods), install python stuff in a directory called `dist-packages`, instead of `site-packages`, so our .so libraries were not being found at runtime by Pyhton.
While trying to find out what can we do to support these kind of installations, on Google Colab you can manually cp the .so files from  `site-packages` to `dist-packages`, like:
```
!cp /usr/local/lib/python3.6/site-packages/*.so /usr/local/lib/python3.6/dist-packages/
```
I don't know how to do this on Trinket, but another option that would work on both environments is to manually add the `site-packages` directory to the `sys.path`:
```python
import sys
sys.path.append('/usr/local/lib/python3.6/site-packages')
from qiskit.providers.aer import Aer
```

**Comment by atilag** [comment]
I have filed a new issue #66  to fix this, so closing this report.
Thanks @quantumjim !
