### ISSUE TITLE
Increase the state vector gradually

### ISSUE THREAD

**Issue by yaelbh** [Qiskit/qiskit-aer#733]
When the simulation starts with the ground state, we can maintain a list of state vectors (initally a vector for every qubit, each of size 2), which can be unified by 2-qubit gates.

**Comment by yaelbh** [comment]
Operations on different vectors can be done in parallel.

**Comment by yaelbh** [comment]
Do we want to do anything with it? If not then we can close.

**Comment by chriseclectic** [comment]
I think this is would be adding an entirely new statevector simulation method based on a full circuit tensor network contraction rather than the current iterative gate-by-gate update (eg like Cyclops tensor framework simulator from John and Ed's 64-qubit simulation paper for example). I'll close for now since but it is something that could potentially be revisited in the future.
