### ISSUE TITLE
Pulse system model incosistently using dict based access

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-aer#741]
### Information

- **Qiskit Terra version**: master (Aer master and 0.5.1)
- **Python version**: 3.8
- **Operating system**: OSX

### What is the current behavior?
There is a pulse simulator mock backend test failure in `FakeBackendsTest.test_transpile_schedule_and_assemble`:
```python
        # Setup freqs for the channels
        freqs = OrderedDict()
        for key in self.hamiltonian._channels:
            chidx = int(key[1:])
            if key[0] == 'D':
                freqs[key] = qubit_lo_freq[chidx]
            elif key[0] == 'U':
                freqs[key] = 0
                for u_lo_idx in self.u_channel_lo[chidx]:
>                   if u_lo_idx['q'] < len(qubit_lo_freq):
E                   TypeError: 'UchannelLO' object is not subscriptable

/opt/miniconda3/lib/python3.8/site-packages/qiskit/providers/aer/pulse/pulse_system_model.py:220: TypeError
```

**Comment by mtreinish** [comment]
I was wondering how this went uncaught by the terra tests (because we install aer in some jobs) and the failing test was introduced in Qiskit/qiskit-terra#3797 and was put in the wrong path. So the configured discovery didn't find the tests. So we haven't been running them. This has been corrected in https://github.com/Qiskit/qiskit-terra/pull/4424
