### ISSUE TITLE
OpenBLAS Warning flooding

### ISSUE THREAD

**Issue by obliviateandsurrender** [Qiskit/qiskit-aer#76]
### Informations

- **Qiskit Aer version**: 1.16.1
- **Python version**: 3.5.4/3.6.7
- **Operating system**: Linux Mint 18.3

### What is the current behavior?
While running it in my local machine/HPC, I get multiple warnings for `OpenBLAS Warning: Detect OpenMP Loop and this application may hang. Please rebuild the library with USE_OPENMP=1 option.` How do I get rid of it? Does this warning affect my results/speed in any way?

**Comment by atilag** [comment]
Hi @obliviateandsurrender, got a few questions:
Have you installed `aer` through `pip` or did you build it by yourself?
Can you post a sample program where to reproduce this warning message?

**Comment by obliviateandsurrender** [comment]
1. I've installed it via `pip`. 
2. I was trying to run a tutorial from this [section](https://github.com/Qiskit/qiskit-tutorials/blob/master/community/aqua/chemistry/lih_uccsd.ipynb).

**Comment by nonhermitian** [comment]
By default openblas is built with `pthreads` and not `openmp`.  That warning happens when the `pthreads` blas is called in an omp section.  In order to get rid of that, you would have to build openblas with the `openmp` option
```
make clean
make USE_OPENMP=1
make install
```
and then build Aer against that.  I believe that some people just disable the warning in source because it is annoying.
