### ISSUE TITLE
qasm_simulator exits with 0 return code even when it errors

### ISSUE THREAD

**Issue by sdague** [Qiskit/qiskit-aer#86]
### Informations

- **Qiskit Aer version**:

Qiskit Aer: 0.1.1

- **Python version**:

Python 3.6

- **Operating system**:

Ubuntu 18.04

### What is the current behavior?

When the qasm_simulator executable has an error it returns a 0 exit code, which traditionally means success.

### Steps to reproduce the problem

Download and unzip the following test file (or any other file that causes a failure) - 
[fail.json.gz](https://github.com/Qiskit/qiskit-aer/files/2962744/fail.json.gz)

run: `./qasm_simulator fail.json`

echo $?

The return code will be 0, even though you'll get "success": false, and "status": "ERROR: ..."

### What is the expected behavior?

exit code that is not 0

**Comment by chriseclectic** [comment]
At the moment I believe the standalone simulator only returns the exit code 1 if it crashes and does not return any result output (typically because the cmd arguments or input file was invalid).

If it returns a valid result output json (according to schema spec) it is returning exit code 0, even if that output has `"success": false`. The cases with success: false could be changed to a different exit code though, maybe 2?

**Comment by sdague** [comment]
exit with 2 would be fine. Any non zero return code is good to know that there was a failure. Otherwise right now we're filtering output which is pretty error prone.

Thanks!

**Comment by atilag** [comment]
What's the expected behavior if we run a list of experiments, but only one or some of them fail? Are we losing the ones that have sucessfully run? Shall we return something different than 0?

**Comment by chriseclectic** [comment]
We could do:

**Comment by chriseclectic** [comment]
We could do
* `0`: life is good
* `1`: failed loading command line options or qobj file
* `2`: qobj loaded and executed with result `status: ERROR`
* `3`: qobj loaded and executed with result `status: COMPLETED` and at least one experiment has failed
