### ISSUE TITLE
Snapshot types that can be removed

### ISSUE THREAD

**Issue by yaelbh** [Qiskit/qiskit-aer#896]
### What is the expected behavior?

In `statevector_state.hpp`:
```
// Snapshots
  {"statevector", "memory", "register", "probabilities",
    "probabilities_with_variance", "expectation_value_pauli",
    "density_matrix", "density_matrix_with_variance",
    "expectation_value_pauli_with_variance",
    "expectation_value_matrix_single_shot", "expectation_value_matrix",
    "expectation_value_matrix_with_variance",
    "expectation_value_pauli_single_shot"}
```
Do all these types still exist?

**Comment by chriseclectic** [comment]
Yes the all still exist, though some are never really used (like memory, and registers).

I think we could consider deprecating the matrix expectation values and only supporting Pauli expectation values (since arbitrary matrices can always be converted into SparsePauliOp to run as pauli expectation values.)
