### ISSUE TITLE
How to simulate decoherence noise quantum circuits in qiskit-aer

### ISSUE THREAD

**Issue by NicolasYL** [Qiskit/qiskit-aer#926]
### Informations

- **Qiskit AER version**: latest
- **Operating system**: win10

### Questions?

Hello，everyone! I am a novice in quantum learning.
So far， I have tried to use qiskit-aer to simulate **Bit flip 、Phase flip、Bit-phase flip、Amplitude damping and phase 
damping** and many more noise models. But i don‘t know how to  simulate decoherence noise in qiskit-aer.

So i want to ask some questions:
1. How to generate karus operators or matrixs about decoherence noise? Is it the same way as simulating Amplitude damping？As far as i know ，decoherence noise model cantains 3 or more params，how to combine them ？

2.Can someone provide some relevant papers about decoherence noise simulation？More precisely，about the principle of the algorithm. So far，I have read **Quantum Information and Quantum Noise  by Gabriel T. Landi** and Decoherence and open quantum sytems and many more ，but unfortunately I didn't get any help.

THANKS A LOT !

**Comment by chriseclectic** [comment]
Closing since this is off topic for aer development.

There is no single "decoherence noise model", decoherence is a general term for a variety of noise types in open quantum systems. How you get the Kraus terms depends on the specific process you want to model (eg amplitude damping, dephasing etc). Often they are derived from a master equation.

I suggest looking up some more text books or lecture notes for theory of open quantum systems that include noise for specific systems (like superconducting qubits, spin qubits etc), or asking on stack exchange for more help.
