### ISSUE TITLE
Snapshot to return a single amplitude on MPS

### ISSUE THREAD

**Issue by merav-aharoni** [Qiskit/qiskit-aer#928]
### What is the expected behavior?
In order to use the `MPS simulation_method`, @gadial requested a snapshot that returns a single amplitude of the `statevector`, without computing the entire `statevector`.
This functionality is useful for MPS, because it saves computing the entire `statevector`, if not needed. 
**Question:** Is this useful for other `simulation_methods`?
The interface can look something like:
`circ.snapshot_amplitude("my amp", ["010001"])`

**Comment by chriseclectic** [comment]
I've been meaning to add this functionality for the statevector simulator for awhile, so it should be added for statevector, statevector_gpu, and MPS.

I would make it specify a list of amplitudes (as either as strings or ints) and then return the array of complex numbers for all specified amplitudes. If the params is the full range `[0, ..., n-1]` then the output should be identical to the statevector snapshot.

It could also be convenient to allow a qubits argument, so that the strings/ints are the values for that qubit mask, with all other qubits assumed to be the 0-state for the full amplitude.

**Comment by merav-aharoni** [comment]
@chriseclectic , a few questions:

1. Should this be a new snapshot or a new parameter of the `statevector` snapshot. We could add a parameter "amplitudes" as
follows:
`qc.snapshot_statevector("sv", amplitudes = ["0011", "0111"])`
2. Should we allow the amplitudes to appear in mask form? For example, the above could also be specified as 
`amplitudes = ["0X11"]`
3. I am not sure what you mean by a "qubits argument." The current statevector snapshot does not support a partial subset of the qubits.

**Comment by chriseclectic** [comment]
A new snapshot. Something like

```python
class SnapshotAmplitudes:
    def __init__(self, label: str, params: List[int], num_qubits=0):
```

And it should assemble to a qobj instruction
````python
QasmQobjInstruction(
    name='snapshot',
    snapshot_type='amplitudes',
    label='label',
    qubits=[0, ..., N-1],
    params=[int0, int1, ..]
)
````
where params are stored as ints rather than bitstrings.

From python side we could also allow bit-string inputs for params and convert them to ints when constructing the python object. 

The qubits argument is another way of specifying masks. Ie the input params are applied to the specified qubit positions and all other qubits in zero (though you could set a custom value other than zero to be more general like in your example). ie if you had `(["00", "01", "10", "11"], qubits=[1, 3])` would be equivalent to `(["0000", "0010", "1000", "1010"])` for a 4-qubit statevector. 

Any fancy masking could be done on the python side too and converted to list of int params so I don't think we need to worry about it for the first iteration.
