### ISSUE TITLE
Not able to install qiskit-aer-gpu

### ISSUE THREAD

**Issue by KillerStrike17** [Qiskit/qiskit-aer#929]
### Informations

- **Qiskit Aer version**: Tried on two versions 0.6.1 &0.5.2
- **Python version**: 3.7.6
- **Operating system**: Windows

### What is the current behavior?

![image](https://user-images.githubusercontent.com/25988007/93022934-5cc87100-f609-11ea-8b5b-d1d2c22feb56.png)

### Steps to reproduce the problem

just run thew qiskit-aer-gpu install command

### What is the expected behavior?

it should install

**Comment by Kaori-Sarin** [comment]
I am facing the same error, unable to find any fix. Please direct me to one if possible.

**Comment by mtreinish** [comment]
There is no `qiskit-aer-gpu` package on Windows. We're only able to build and publish it on Linux which you can see with the list of available binary wheels on: https://pypi.org/project/qiskit-aer-gpu/#files If you'd like to run the GPU simulator on windows you'll have to build it from source following the instructions in the contributing guide: https://github.com/Qiskit/qiskit-aer/blob/master/CONTRIBUTING.md#building-with-gpu-support however note the GPU simulator is not tested or supported on windows so there are likely issues there. I'm closing this since there is not anything to fix here, please feel free to reopen this if I'm missing something.

**Comment by Shubham-patel-q** [comment]
I am facing same problem in my Linux device.

**Comment by gadial** [comment]
> I am facing same problem in my Linux device.

We have been unable to create wheels for `qiskit-aer-gpu` for some time now. I hope it can be still compiled from source on some devices.
