### ISSUE TITLE
Re-evaluate default thresholds for OpenMP and Fusion

### ISSUE THREAD

**Issue by chriseclectic** [Qiskit/qiskit-aer#954]
### What is the expected behavior?

With the recent changes to the gate fusion algorithm and including SIMD we should re-evaluate the default threshold values for enabling OpenMP, and for enabling gate fusion for the different qubitvector based simulations States (Statevector, DensityMatrix, Unitary, Superoperator) to ensure good default performance.

**Comment by hhorii** [comment]
I guess that the current thresholds are not so bad. Because best thresholds depend on machines and circuits, if performance is required, users can calibrate parameters `max_parallel_threads`, `max_parallel_experiments`, and `max_parallel_shots`.
We may need to continuously define default values of thresholds for each release.
