### ISSUE TITLE
Incorrect output for CH simulator for some simple circuits with t gates

### ISSUE THREAD

**Issue by chriseclectic** [Qiskit/qiskit-aer#98]
### Informations

- **Qiskit Aer version**: master
- **Python version**: 3.6
- **Operating system**: MacOS

### What is the current behavior?

@padraic-padraic I noticed some unusual behaviour while testing the CH simulator. If I run a bell preparation circuit and insert a `t` gate (which should not change the output) instead of returning `{'00': shots / 2, '11': shots / 2}`, it appears to return `{'00' : shots}` or `{'11': shots}`.

### Steps to reproduce the problem

Test circuit that should return `counts = {'00': shots / 2, '11': shots / 2}` since the final t-gate commutes with the last measurement.

```python
from qiskit import QuantumCircuit, QuantumRegister, ClassicalRegister, execute
from qiskit.providers.aer import QasmSimulator
import numpy as np

# Test Circuit
qr = QuantumRegister(2, 'qr')
cr = ClassicalRegister(2, 'cr')
circ = QuantumCircuit(qr, cr)
circ.h(qr[0])
circ.cx(qr[0], qr[1])
circ.t(qr[0])
circ.measure(qr, cr)

# Execute
result = execute(circ, QasmSimulator(), backend_options={"method": "ch"}).result()
counts = result.get_counts(circ)
```

This returns *either* `counts ={'00' : 1024}` or `counts = {'11' : 1024}` with roughly even probability.

### What is the expected behavior?

It should return something close to `counts ={'00' : 512, '11': 512}`. 

### Suggested solutions

I'm not sure, I mentioned the problem to Sergey and he is also looking into.

**Comment by padraic-padraic** [comment]
Hey Chris,

This is exactly the kind of caveat I mentoned when it comes to output value estimation.

In the first case, the Bell preparation circuit is purely clifford, so we're sampling using the method for the CH state outlined at the end of  section IV A in

However, for the case of a single T gate, then we have introduced multiple states in the decomposition and the simulator is using the Monte Carlo method to estimate the output distribution. Because there's only a single measurement stage, it tries to optimise by only mixing the markov chain once and then taking `n_shots` further samples. 

But, because our distribution looks like `| _ _ | ` (in the computational basis), then the markov chain picks and random input state, converges to one of the two peaks, and then is stuck there as no single bit moves are possible. Try rerunning the circuit with `ch_mixing_time=100` and `ch_disable_measurement_opt=True`.

Given this can come up with relatively simple cirucits, let me know if you think we should alter the default behaviour of the method to rerun the monte carlo for each sample. The method is better suited to cases where the output distribution is going to be non-zero on most amplitudes.

**Comment by chriseclectic** [comment]
@padraic-padraic adding `{"ch_disable_measurement_opt": True}` seems to fix this issue so maybe that is a safer default value?

**Comment by padraic-padraic** [comment]
Yeah, if you notice in the [tests](test/terra/test_ch_simulator.py) I set that parameter for a lot of them, while also dialing down the mixing time to speedup repeat shots. I'll make that change and push it with the segmentation fault fix once I've tracked it down.

**Comment by chriseclectic** [comment]
Sounds good! Would you be interested in making a Juptyer tutorial for using the CH simulator that we can keep in [qiskit-tutorials/aer](https://github.com/Qiskit/qiskit-tutorials/tree/master/qiskit/aer) to explain some of these options and best practices / possible pitfalls when using the CH simulator?

**Comment by padraic-padraic** [comment]
Yeah, I'd be happy to do that! I'd actually considered writing a blog post or something similar to help act as a users guide for the method.

**Comment by chriseclectic** [comment]
A blog post to go with it would be great too!
